import asyncio
import os
import sys
import json

# MCP client components
from typing import Optional
from contextlib import AsyncExitStack
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client

from google import genai
from google.genai import types
from google.genai.types import Tool, FunctionDeclaration
from google.genai.types import GenerateContentConfig

from dotenv import load_dotenv

load_dotenv()

def clean_schema(schema):
    if isinstance(schema, dict):
        schema.pop("title", None)

        if "properties" in schema and isinstance(schema['properties'], dict):
            for key in schema["properties"]:
                schema["properties"][key] = clean_schema(schema["properties"][key])
    return schema

def convert_mcp_tools_to_gemini(mcp_tools):
    """
    Converts MCP tool definitions to the correct format for gemini API function calling

    Args:
        mcp_tools (list): List of MCP tool objects with 'name', 'description' and 'input'

    Returns:
        list: List of Gemini Tool objects with properly formatted function declarations.
    """
    gemini_tools = []

    for tool in mcp_tools:
        parameters = clean_schema(tool.inputSchema)

        function_declaration = FunctionDeclaration(
            name=tool.name,
            description=tool.description,
            parameters=parameters
        )

        # Wrap in tool object
        gemini_tool = Tool(function_declarations=[function_declaration])
        gemini_tools.append(gemini_tool)  # Fixed: was appending gemini_tools to itself

    return gemini_tools


class MCPClient:
    def __init__(self):
        """Initialize the MCP Client and configure the Gemini API"""
        self.session: Optional[ClientSession] = None
        self.exit_stack = AsyncExitStack()

        gemini_api_key = os.getenv("GOOGLE_API_KEY")

        if not gemini_api_key:
            raise ValueError("Gemini API Key not found!!!!!")
        
        self.genai_client = genai.Client(api_key=gemini_api_key)  # Fixed: genai_clinet -> genai_client

    async def connect_to_server(self, server_script_path: str):
        """
        Connect to the MCP server and list available tools.
        """
        command = "python" if server_script_path.endswith('.py') else "node"  # Fixed: Added dot before py

        server_params = StdioServerParameters(command=command,
                                              args=[server_script_path])
        
        stdio_transport = await self.exit_stack.enter_async_context(stdio_client(server_params))

        self.stdio, self.write = stdio_transport

        self.session = await self.exit_stack.enter_async_context(ClientSession(self.stdio, self.write))

        await self.session.initialize()

        response = await self.session.list_tools()
        tools = response.tools

        print("\nConnected to server with tools", [tool.name for tool in tools])

        self.function_declarations = convert_mcp_tools_to_gemini(tools)

    async def process_query(self, query: str) -> str:
        """
        Process a user query using the Gemini API and execute tool calls if needed.

        Args:
            query (str): the user's input query

        Returns:
            str: The response generated by the Gemini API
        """
        user_prompt_content = types.Content(
            role='user',
            parts=[types.Part.from_text(text=query)]
        )

        response = self.genai_client.models.generate_content(  # Fixed: genai_clinet -> genai_client
            model="gemini-2.0-flash-001",
            contents=[user_prompt_content],
            config=types.GenerateContentConfig(
                tools=self.function_declarations
            ),
        )

        final_text = []
        # Removed unnecessary assistant_message_content declaration

        for candidate in response.candidates:
            if candidate.content.parts:
                for part in candidate.content.parts:
                    if isinstance(part, types.Part):
                        if part.function_call:
                            function_call_part = part
                            tool_name = function_call_part.function_call.name  # Fixed: tools_name -> tool_name
                            tool_args = function_call_part.function_call.args  # Fixed: tools_args -> tool_args

                            print(f"\nGemini requested Tool call {tool_name} with args {tool_args}")  # Fixed: f-string formatting

                            try:
                                result = await self.session.call_tool(tool_name, tool_args)  # Fixed variable names
                                function_response = {"result": result.content}
                            except Exception as e:
                                function_response = {"error": str(e)}

                            function_response_part = types.Part.from_function_response(
                                name=tool_name,  # Fixed variable name
                                response=function_response
                            )

                            function_response_content = types.Content(
                                role='tool',
                                parts=[function_response_part]
                            )

                            response = self.genai_client.models.generate_content(  # Fixed: genai_clinet -> genai_client
                                model='gemini-2.0-flash-001',
                                contents=[
                                    user_prompt_content,
                                    function_call_part,
                                    function_response_content
                                ],
                                config=types.GenerateContentConfig(
                                    tools=self.function_declarations
                                ),
                            )

                            final_text.append(response.candidates[0].content.parts[0].text)
                        else:
                            final_text.append(part.text)
        return "\n".join(final_text)

    async def chat_loop(self):
        print("\nMCP Client Started: Type 'quit' to exit.")  # Fixed: ]n -> \n

        while True:
            query = input("\nQuery: ").strip()

            if query.lower() == "quit":
                break

            response = await self.process_query(query)

            print("\n" + response)

    async def cleanup(self):
        await self.exit_stack.aclose()


async def main():
    if len(sys.argv) < 2:
        print("Usage: python client.py <path_to_server_script>")  # Fixed: Usuage -> Usage
        sys.exit(1)

    client = MCPClient()

    try:
        await client.connect_to_server(sys.argv[1])
        await client.chat_loop()
    finally:
        await client.cleanup()


if __name__ == "__main__":
    asyncio.run(main())